## Tranformando o conjunto de treinamento em cvs

> Autor: Dayvson Silva

> Data: 03/09/2020

> Taferas para realizar a transformação

- Ler os arquivos binários que armazenam os

- Separar os dados em entradas e saidas

- Criar uma estrutura para preencher com os dados

- Exportar os dados para um arquivo csv

## Importando as bibliotecas usadas nas tarefas

In [3]:
import numpy as np
import pandas as pd
import os

## Lendo os arquivos com numpy

### Visualizando o shape dos arquivos

In [6]:
def show_shape(full_path, file_data):
    array = np.fromfile(file=full_path)
    print("No arquivo", file_data, "tem", array.shape, "itens.")

def run_files_data(path_data = ''):
    for file_data in os.listdir(path_data):
        full_path = os.path.join(path_data, file_data)
        show_shape(full_path, file_data)

In [7]:
run_files_data('rna-2020.1-pp2-data/')

No arquivo data0.txt tem (1750,) itens.
No arquivo data1.txt tem (1800,) itens.
No arquivo data2.txt tem (1800,) itens.
No arquivo data3.txt tem (1800,) itens.
No arquivo dataAll.txt tem (3000,) itens.
No arquivo dataHoldout.txt tem (2400,) itens.


### visualizando o conteúdo dos arquivos

In [8]:
np.fromfile('rna-2020.1-pp2-data\data0.txt')

array([1.49351310e-03, 4.78163211e-04, 0.00000000e+00, ...,
       1.55399036e+88, 4.76792279e-04, 3.05175781e-05])

In [9]:
np.fromfile('rna-2020.1-pp2-data\data1.txt')

array([ 0.13658687, -0.16460088,  0.        , ...,  0.99252852,
        1.06937678,  1.        ])

In [11]:
np.fromfile('rna-2020.1-pp2-data\data2.txt')

array([ 0.00553719, -0.02079496,  1.        , ...,  0.99828858,
        0.99300766,  0.        ])

In [12]:
np.fromfile('rna-2020.1-pp2-data\data3.txt')

array([ 0.06162809, -0.1242566 ,  0.        , ...,  1.05935906,
        0.93900834,  1.        ])

In [16]:
np.fromfile('rna-2020.1-pp2-data\dataAll.txt')

array([-363.7884,  244.1423,    0.    , ..., -140.147 ,  734.0983,
          0.    ])

In [17]:
np.fromfile('rna-2020.1-pp2-data\dataHoldout.txt')

array([-0.29322959, -0.09065359,  1.        , ...,  0.72930655,
        0.93224271,  0.        ])

## Reshape os conjuntos de dados

In [32]:


def reshape_dataset(full_path):
    try:
        array = np.fromfile(full_path)
        number_samples = array.shape[0]//3
        array = array.reshape(number_samples, 3)
        return array
    except:
        return ''

def run_files_data(path_data):
    datasets_list = []
    for file_data in os.listdir(path_data):
        full_path = os.path.join(path_data, file_data)
        dataset = reshape_dataset(full_path)
        if dataset != '':
            datasets_list.append(dataset)
    print(len(datasets_list))

In [33]:
run_files_data('rna-2020.1-pp2-data/')

5


In [52]:
from pprint import pprint
file_data = np.fromfile('rna-2020.1-pp2-data/data0.txt')
k = 0
for i in range(0, 100, 3):
    for j in range(k, i):
        k = i
        pprint(file_data[j])#, end='\t\t\t')
    print()



0.0014935130967365896
0.0004781632108761179
0.0

7.09001989770296e+280
3.43577405274585e-310
0.0004730224609375

2.3224068453857122e+54
3.43577586597467e-310
0.00128173828125

5.764064589227119e+20
3.43575256195106e-310
0.0001068115234375

6.283109597865357e-86
5.24258922e-315
5.6934889212993654e-216

0.0007399861919967622
3.1e-322
0.0004767922792309198

0.00047930036479484976
0.0
0.0004738718845489382

1.7381481825745278e-307
3.0517578125e-05
1.0910704693585321e-249

3.44931426843504e-310
2.6090274071679933e+213
8.424190393876717e+68

1.342103840487e-312
0.00048023462295532227
5.389771095531828e-05

5.24258669e-315
9.630940621718764e-05
1.5194685497468057e-148

2.0471274e-317
9.3347340630038e-187
1.2283765217210932e-129

7.9994e-320
3.4060951045503045e-105
0.00320398667449942

3.1e-322
0.00047677804237043764
0.0004772094584856202

0.0
0.00047680648229419327
0.00047309681038941974

0.0
1.6871650879463898e-298
3.43577598600496e-310

1.709852201561616e+218
4.0692300929036045e+44
3.43574